server:
    port: 8081
    forward-headers-strategy: framework
spring:
    application:
        name: ms-company
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${COMPANY_DB_HOST}:${COMPANY_DB_PORT}/${COMPANY_DB_NAME}?createDatabaseIfNotExist=true&${COMPANY_DB_OPTS}&${COMPANY_DB_SESSION_OPTS}
        username: ${COMPANY_DB_USER}
        password: ${COMPANY_DB_PASSWORD}
        hikari:
            poolName: Hikari
            auto-commit: false
            connection-test-query: SELECT 1
    jpa:
        show-sql: true
        open-in-view: false
        database: default
        hibernate.ddl-auto: none
        database-platform: org.hibernate.dialect.MySQLDialect
        properties.hibernate:
            jdbc.time_zone: UTC
    liquibase:
        enabled: true
        change-log: classpath:/liquibase/master.xml
        default-schema: company_db
    cloud:
      openfeign:
        client:
            config:
                geocode-client:
                    url: ${COMPANY_GEOCODE_BASE_URL}
                    connect-timeout: 5000
                    read-timeout: 5000
                cnpj-ws-client:
                    url: ${COMPANY_CNPJ_WS_BASE_URL}
                    connect-timeout: 5000
                    read-timeout: 5000
                default:
                    default-request-headers:
                        Accept: application/json
                    retryer: feign.Retryer.Default
                    connectTimeout: 5000
                    readTimeout: 5000
                    loggerLevel: basic
            refresh-enabled: true
eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVICE_URL}/eureka
springdoc:
    cache:
        disabled: true
