services:
  company.mysql:
    container_name: company.mysql
    hostname: localhost
    image: mysql:8.0.30
    command: --max_allowed_packet=512M
    volumes:
      - db:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: company
    networks:
      - bubble
    ports:
      - '8307:3306'

networks:
  bubble:
    external: true